"""Pure, versioned admissions-fit domain contract."""

from domain.admissions_fit.calculator import ALGORITHM_VERSION, estimate_admissions_fit
from domain.admissions_fit.models import (
    AlgorithmVersion,
    Assessment,
    CaveatCode,
    EvidenceLevel,
    FitBasis,
    FitCategory,
    FitEstimate,
    FitFactor,
    FitSignal,
    FitSignalSource,
    GpaBucket,
    GpaDistribution,
    ObservedDecimal,
    RankDistribution,
    SchoolFitInputs,
    SchoolSatBands,
    ScoreBand,
    StudentFitInputs,
    TestPolicy,
    UnavailableFactor,
    UnavailableReason,
)

__all__ = [
    "ALGORITHM_VERSION",
    "AlgorithmVersion",
    "Assessment",
    "CaveatCode",
    "EvidenceLevel",
    "FitBasis",
    "FitCategory",
    "FitEstimate",
    "FitFactor",
    "FitSignal",
    "FitSignalSource",
    "GpaBucket",
    "GpaDistribution",
    "ObservedDecimal",
    "RankDistribution",
    "SchoolFitInputs",
    "SchoolSatBands",
    "ScoreBand",
    "StudentFitInputs",
    "TestPolicy",
    "UnavailableFactor",
    "UnavailableReason",
    "estimate_admissions_fit",
]
