/**
 * CounselleVerifiedBadge — the once-per-card trust mark for our own figures.
 *
 * Provenance is a property of the card, not of each row: instead of stamping
 * "Counselle" beside every number, one calm badge in the card header attests
 * the whole thing. Hovering says, in plain words, what "verified" means and —
 * the part students actually worry about — that the figures aren't invented by
 * the assistant.
 */
import * as HoverCard from '@radix-ui/react-hover-card';
import { cn } from '@librechat/client/utils';
import CounselleMark from '@/components/citations/CounselleMark';

export default function CounselleVerifiedBadge({ className }: { className?: string }) {
  return (
    <HoverCard.Root openDelay={120} closeDelay={80}>
      <HoverCard.Trigger asChild>
        <button
          type="button"
          className={cn(
            'group/verified -mx-1 inline-flex items-center gap-1.5 rounded-md px-1 py-0.5',
            'text-[11px] font-medium leading-none text-text-tertiary',
            'transition-colors hover:text-text-secondary',
            'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring',
            className,
          )}
        >
          <CounselleMark sizeClass="h-[15px] w-[15px]" />
          <span>Counselle-verified</span>
        </button>
      </HoverCard.Trigger>
      <HoverCard.Portal>
        <HoverCard.Content
          side="bottom"
          align="end"
          sideOffset={8}
          collisionPadding={12}
          className={cn(
            'z-50 w-72 max-w-[calc(100vw-1.5rem)] overflow-hidden rounded-2xl',
            'border border-border-light bg-surface-chat p-3.5 shadow-xl',
            'data-[state=open]:animate-in data-[state=closed]:animate-out',
            'data-[state=open]:fade-in-0 data-[state=closed]:fade-out-0',
            'data-[state=open]:zoom-in-95 data-[state=closed]:zoom-out-95',
            'motion-reduce:animate-none',
          )}
        >
          <div className="flex items-center gap-2">
            <CounselleMark sizeClass="h-5 w-5" />
            <span className="text-[13px] font-semibold text-text-primary">Counselle-verified</span>
          </div>
          <p className="mt-2 text-[12px] leading-relaxed text-text-secondary">
            These figures come from official college data we maintain and keep current. Looked up
            for you, never generated by the assistant.
          </p>
        </HoverCard.Content>
      </HoverCard.Portal>
    </HoverCard.Root>
  );
}
