import type { ExploreSchool } from "@/features/schools/explore/explore-types";

/*
 * ============================================================================
 * FIXTURES. EVERY NUMBER BELOW IS FABRICATED.
 *
 * This file exists so the Explore surface can be designed and reviewed
 * before the backend filter API exists. It must be replaced by a real query
 * against the CDS Library views before this tab is shown to a student —
 * AGENTS.md principle 3 is not negotiable, and a plausible number is a more
 * dangerous lie than an obvious one.
 * ============================================================================
 *
 * The set is deliberately WORSE than reality on coverage. Four schools are
 * missing at least one metric, four carry a severe test-band caveat (under
 * 50% submitted), and one has no admit rate at all so the Unknown verdict
 * path is exercised. A clean fixture set hides exactly the render paths
 * that matter.
 */

export const exploreFixtures: ExploreSchool[] = [
  {
    unitid: "130794",
    name: "Yale University",
    city: "New Haven",
    state: "CT",
    websiteUrl: "https://www.yale.edu",
    control: "private",
    undergraduates: 6_600,
    admitRate: { value: 4.6, basis: "overall" },
    testBand: { p25: 1500, p75: 1560, submittedPercent: 62 },
    cost: { amount: 87_400, basis: "private" },
    needMet: 100,
    meritAid: null,
    gradFourYear: 88,
    gradSixYear: 97,
    retention: 99,
    applicationFee: 80,
    testPolicy: "optional",
    studentsPerFaculty: 6,
    housingPercent: 84,
    greekPercent: 12,
    outOfStatePercent: 92,
    internationalPercent: 12,
    genderModel: "coed",
    calendar: "semester",
    rounds: [
      { code: "REA", deadline: "2026-11-01", restrictive: true },
      { code: "RD", deadline: "2027-01-02" },
    ],
    cdsYear: 2025,
    onList: false,
  },
  {
    unitid: "167358",
    name: "Northeastern University",
    city: "Boston",
    state: "MA",
    websiteUrl: "https://www.northeastern.edu",
    control: "private",
    undergraduates: 16_300,
    admitRate: { value: 5.2, basis: "overall" },
    testBand: { p25: 1480, p75: 1550, submittedPercent: 41 },
    cost: { amount: 89_000, basis: "private" },
    needMet: 68,
    meritAid: 22,
    gradFourYear: 82,
    gradSixYear: 89,
    retention: 97,
    applicationFee: 75,
    testPolicy: "optional",
    studentsPerFaculty: 15,
    housingPercent: 47,
    greekPercent: 6,
    outOfStatePercent: 74,
    internationalPercent: 20,
    genderModel: "coed",
    calendar: "semester",
    rounds: [
      { code: "ED", deadline: "2026-11-01" },
      { code: "EA", deadline: "2026-11-01" },
      { code: "ED2", deadline: "2027-01-01" },
      { code: "RD", deadline: "2027-01-01" },
    ],
    cdsYear: 2025,
    onList: false,
  },
  {
    unitid: "166629",
    name: "University of Massachusetts Amherst",
    city: "Amherst",
    state: "MA",
    websiteUrl: "https://www.umass.edu",
    control: "public",
    undergraduates: 24_200,
    admitRate: { value: 58, basis: "in-state" },
    testBand: { p25: 1300, p75: 1450, submittedPercent: 88 },
    cost: { amount: 33_000, basis: "in-state" },
    needMet: 62,
    meritAid: 41,
    gradFourYear: 71,
    gradSixYear: 84,
    retention: 91,
    applicationFee: 85,
    testPolicy: "optional",
    studentsPerFaculty: 17,
    housingPercent: 61,
    greekPercent: 9,
    outOfStatePercent: 28,
    internationalPercent: 5,
    genderModel: "coed",
    calendar: "semester",
    rounds: [
      { code: "EA", deadline: "2026-11-05" },
      { code: "RD", deadline: "2027-01-15" },
    ],
    cdsYear: 2025,
    onList: true,
  },
  {
    unitid: "168342",
    name: "Williams College",
    city: "Williamstown",
    state: "MA",
    websiteUrl: "https://www.williams.edu",
    control: "private",
    undergraduates: 2_100,
    admitRate: { value: 8.5, basis: "overall" },
    testBand: { p25: 1490, p75: 1560, submittedPercent: 55 },
    cost: { amount: 85_000, basis: "private" },
    needMet: 100,
    meritAid: null,
    gradFourYear: 91,
    gradSixYear: 95,
    retention: 98,
    applicationFee: 65,
    testPolicy: "optional",
    studentsPerFaculty: 6,
    housingPercent: 94,
    greekPercent: 0,
    outOfStatePercent: 87,
    internationalPercent: 10,
    genderModel: "coed",
    calendar: "semester",
    rounds: [
      { code: "ED", deadline: "2026-11-15" },
      { code: "RD", deadline: "2027-01-06" },
    ],
    cdsYear: 2025,
    onList: false,
  },
  {
    unitid: "196097",
    name: "Stony Brook University",
    city: "Stony Brook",
    state: "NY",
    websiteUrl: "https://www.stonybrook.edu",
    control: "public",
    undergraduates: 17_900,
    admitRate: { value: 49, basis: "overall" },
    testBand: { p25: 1290, p75: 1450, submittedPercent: 71 },
    cost: { amount: 30_000, basis: "in-state" },
    needMet: null,
    meritAid: 34,
    gradFourYear: 60,
    gradSixYear: 77,
    retention: 88,
    applicationFee: 50,
    testPolicy: "blind",
    studentsPerFaculty: 18,
    housingPercent: 52,
    greekPercent: 4,
    outOfStatePercent: 12,
    internationalPercent: 14,
    genderModel: "coed",
    calendar: "semester",
    rounds: [
      { code: "EA", deadline: "2026-11-01" },
      { code: "RD", deadline: "2027-01-15" },
    ],
    cdsYear: 2024,
    onList: false,
  },
  {
    unitid: "243780",
    name: "Purdue University",
    city: "West Lafayette",
    state: "IN",
    websiteUrl: "https://www.purdue.edu",
    control: "public",
    undergraduates: 37_900,
    admitRate: { value: 50, basis: "overall" },
    testBand: { p25: 1210, p75: 1450, submittedPercent: 66 },
    cost: { amount: 24_000, basis: "out-of-state" },
    needMet: 55,
    meritAid: 46,
    gradFourYear: 60,
    gradSixYear: 84,
    retention: 93,
    applicationFee: 60,
    testPolicy: "optional",
    studentsPerFaculty: 15,
    housingPercent: 38,
    greekPercent: 20,
    outOfStatePercent: 44,
    internationalPercent: 12,
    genderModel: "coed",
    calendar: "semester",
    rounds: [
      { code: "EA", deadline: "2026-11-01" },
      { code: "RD", deadline: "2027-01-15" },
    ],
    cdsYear: 2025,
    onList: false,
  },
  {
    unitid: "227757",
    name: "Rice University",
    city: "Houston",
    state: "TX",
    websiteUrl: "https://www.rice.edu",
    control: "private",
    undergraduates: 4_500,
    admitRate: { value: 7.5, basis: "overall" },
    testBand: { p25: 1500, p75: 1560, submittedPercent: 47 },
    cost: { amount: 78_000, basis: "private" },
    needMet: 100,
    meritAid: 12,
    gradFourYear: 87,
    gradSixYear: 95,
    retention: 97,
    applicationFee: 75,
    testPolicy: "optional",
    studentsPerFaculty: 6,
    housingPercent: 74,
    greekPercent: 0,
    outOfStatePercent: 55,
    internationalPercent: 13,
    genderModel: "coed",
    calendar: "semester",
    rounds: [
      { code: "ED", deadline: "2026-11-01" },
      { code: "RD", deadline: "2027-01-04" },
    ],
    cdsYear: 2025,
    onList: false,
  },
  {
    unitid: "231174",
    name: "University of Vermont",
    city: "Burlington",
    state: "VT",
    websiteUrl: "https://www.uvm.edu",
    control: "public",
    undergraduates: 11_400,
    admitRate: { value: 62, basis: "out-of-state" },
    testBand: { p25: 1190, p75: 1370, submittedPercent: 33 },
    cost: { amount: 36_000, basis: "in-state" },
    needMet: 48,
    meritAid: 63,
    gradFourYear: 62,
    gradSixYear: 74,
    retention: 86,
    applicationFee: 55,
    testPolicy: "blind",
    studentsPerFaculty: 17,
    housingPercent: 47,
    greekPercent: 8,
    outOfStatePercent: 76,
    internationalPercent: 3,
    genderModel: "coed",
    calendar: "semester",
    rounds: [
      { code: "EA", deadline: "2026-11-01" },
      { code: "RD", deadline: "2027-01-15" },
    ],
    cdsYear: 2024,
    onList: false,
  },
  {
    unitid: "168218",
    name: "Wellesley College",
    city: "Wellesley",
    state: "MA",
    websiteUrl: "https://www.wellesley.edu",
    control: "private",
    undergraduates: 2_400,
    admitRate: { value: 13, basis: "overall" },
    testBand: { p25: 1440, p75: 1550, submittedPercent: 51 },
    cost: { amount: 84_000, basis: "private" },
    needMet: 100,
    meritAid: null,
    gradFourYear: 88,
    gradSixYear: 92,
    retention: 96,
    applicationFee: 0,
    testPolicy: "optional",
    studentsPerFaculty: 7,
    housingPercent: 96,
    greekPercent: 0,
    outOfStatePercent: 84,
    internationalPercent: 14,
    genderModel: "women",
    calendar: "semester",
    rounds: [
      { code: "ED", deadline: "2026-11-01" },
      { code: "ED2", deadline: "2027-01-01" },
      { code: "RD", deadline: "2027-01-08" },
    ],
    cdsYear: 2025,
    onList: false,
  },
  {
    unitid: "104151",
    name: "Arizona State University",
    city: "Tempe",
    state: "AZ",
    websiteUrl: "https://www.asu.edu",
    control: "public",
    undergraduates: 65_000,
    admitRate: { value: 90, basis: "overall" },
    testBand: null,
    cost: { amount: 34_000, basis: "out-of-state" },
    needMet: 40,
    meritAid: 55,
    gradFourYear: 51,
    gradSixYear: 67,
    retention: 86,
    applicationFee: 70,
    testPolicy: "blind",
    studentsPerFaculty: 19,
    housingPercent: 21,
    greekPercent: 11,
    outOfStatePercent: 40,
    internationalPercent: 8,
    genderModel: "coed",
    calendar: "semester",
    rounds: [
      { code: "Rolling", deadline: null },
      { code: "RD", deadline: "2027-02-01" },
    ],
    cdsYear: 2025,
    onList: false,
  },
  {
    unitid: "126678",
    name: "Colorado College",
    city: "Colorado Springs",
    state: "CO",
    websiteUrl: "https://www.coloradocollege.edu",
    control: "private",
    undergraduates: 2_200,
    admitRate: { value: 15, basis: "overall" },
    testBand: { p25: 1330, p75: 1500, submittedPercent: 44 },
    cost: { amount: 82_000, basis: "private" },
    needMet: 93,
    meritAid: 18,
    gradFourYear: 82,
    gradSixYear: 88,
    retention: 93,
    applicationFee: 60,
    testPolicy: "optional",
    studentsPerFaculty: 9,
    housingPercent: 76,
    greekPercent: 14,
    outOfStatePercent: 82,
    internationalPercent: 8,
    genderModel: "coed",
    calendar: null,
    rounds: [
      { code: "ED", deadline: "2026-11-01" },
      { code: "ED2", deadline: "2027-01-15" },
      { code: "RD", deadline: "2027-01-15" },
    ],
    cdsYear: 2025,
    onList: false,
  },
  {
    unitid: "190567",
    name: "The City College of New York",
    city: "New York",
    state: "NY",
    websiteUrl: "https://www.ccny.cuny.edu",
    control: "public",
    undergraduates: 12_700,
    admitRate: null,
    testBand: null,
    cost: { amount: 19_000, basis: "in-state" },
    needMet: 35,
    meritAid: 12,
    gradFourYear: 24,
    gradSixYear: 55,
    retention: 82,
    applicationFee: 65,
    testPolicy: "blind",
    studentsPerFaculty: 15,
    housingPercent: null,
    greekPercent: 2,
    outOfStatePercent: 4,
    internationalPercent: 9,
    genderModel: "coed",
    calendar: "semester",
    rounds: [{ code: "RD", deadline: "2027-02-01" }],
    cdsYear: 2023,
    onList: false,
  },
];

/** The states present in the fixture set, for the Location filter. */
export const exploreStates: string[] = [
  ...new Set(exploreFixtures.map((school) => school.state)),
].sort();
