/**
 * The golden contract fixtures — the frontend half (B2, wire-contract).
 *
 * Loads the SAME committed JSON files the backend asserts against
 * (`tests/fixtures/protocol/*.json`, generated by
 * `tests/app/test_protocol_fixtures.py` — they live outside the Vite root, so
 * they are read via fs, never imported) and asserts the protocol.ts types
 * accept them: every event passes a per-type shape check typed against
 * `ProtocolEvent`, every transcript entry against `TranscriptEntry`.
 *
 * Drift on either side of the wire = a red test on that side. Regenerate
 * backend-side with `REGEN_PROTOCOL_FIXTURES=1 uv run pytest
 * tests/app/test_protocol_fixtures.py`, then re-run this.
 */
import { readFileSync } from 'node:fs';
import path from 'node:path';
import { describe, expect, test } from 'vitest';
import type {
  ClarifySpec,
  ProtocolEvent,
  RenderSpec,
  SourceEntry,
  TranscriptAssistantEntry,
  TranscriptEntry,
  TranscriptUserEntry,
} from '@/api/protocol';

const FIXTURES_DIR = path.resolve(__dirname, '../../../tests/fixtures/protocol');

function load(name: string): unknown {
  return JSON.parse(readFileSync(path.join(FIXTURES_DIR, `${name}.json`), 'utf-8'));
}

// ── typed shape checks ───────────────────────────────────────────────────────
// Runtime narrowing typed against protocol.ts: if the types change shape,
// these checks stop compiling; if the fixtures change shape, they fail.

const EVENT_TYPES: ReadonlyArray<ProtocolEvent['type']> = [
  'meta',
  'delta',
  'step',
  'thinking',
  'viz',
  'clarify',
  'sources',
  'usage',
  'done',
  'error',
];

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

function assertEvent(raw: unknown): ProtocolEvent {
  expect(isRecord(raw)).toBe(true);
  const obj = raw as Record<string, unknown>;
  expect(obj.v).toBe(1);
  expect(EVENT_TYPES).toContain(obj.type);
  expect(isRecord(obj.data)).toBe(true);
  const event = obj as ProtocolEvent;
  const data = event.data as Record<string, unknown>;
  switch (event.type) {
    case 'meta':
      for (const key of ['trace_id', 'session_id', 'model', 'message_id', 'user_message_id']) {
        expect(typeof data[key], `meta.${key}`).toBe('string');
      }
      break;
    case 'delta':
    case 'thinking':
      expect(typeof data.text).toBe('string');
      break;
    case 'step':
      expect(typeof data.step_id).toBe('string');
      expect(['start', 'end', 'error']).toContain(data.status);
      expect([
        'db_tool',
        'sql',
        'web_search',
        'edu_search',
        'reddit_search',
        'viz',
        'skill',
        'research',
      ]).toContain(data.kind);
      expect(typeof data.label).toBe('string');
      expect('tier' in data).toBe(true);
      break;
    case 'viz':
      assertRenderSpec(data as RenderSpec);
      break;
    case 'clarify':
      assertClarifySpec(data as ClarifySpec);
      break;
    case 'sources':
      expect(Array.isArray(data.sources)).toBe(true);
      for (const entry of data.sources as unknown[]) {
        assertSourceEntry(entry);
      }
      break;
    case 'usage':
      expect(typeof data.input_tokens).toBe('number');
      expect(typeof data.output_tokens).toBe('number');
      expect(typeof data.tool_calls).toBe('number');
      break;
    case 'done':
      expect(['complete', 'awaiting_input', 'cancelled']).toContain(data.status);
      break;
    case 'error':
      expect(typeof data.message).toBe('string');
      expect(typeof data.trace_id).toBe('string');
      break;
  }
  return event;
}

function assertRenderSpec(spec: RenderSpec): void {
  expect(['stat_block', 'comparison_table', 'score_band']).toContain(spec.type);
  expect(typeof spec.title).toBe('string');
  expect(Array.isArray(spec.schools)).toBe(true);
  expect(Array.isArray(spec.rows)).toBe(true);
  for (const row of spec.rows) {
    for (const cell of row.cells) {
      expect(typeof cell.display).toBe('string');
      expect(typeof cell.available).toBe('boolean');
      assertCitation(cell.citation);
    }
  }
}

function assertClarifySpec(spec: ClarifySpec): void {
  expect(typeof spec.question).toBe('string');
  expect(typeof spec.header).toBe('string');
  expect(typeof spec.multi_select).toBe('boolean');
  expect(spec.options.length).toBeGreaterThanOrEqual(2);
  for (const option of spec.options) {
    expect(typeof option.label).toBe('string');
    expect(typeof option.hint).toBe('string');
  }
}

function assertCitation(citation: SourceEntry['citation']): void {
  // C1 — the honesty pin: the two-value tier + the source-name union.
  expect(['official', 'community']).toContain(citation.tier);
  expect(['ipeds', 'scorecard', 'cds', 'web', 'edu', 'reddit']).toContain(citation.source);
  expect(typeof citation.vintage).toBe('string');
}

function assertSourceEntry(raw: unknown): SourceEntry {
  expect(isRecord(raw)).toBe(true);
  const entry = raw as SourceEntry;
  expect(typeof entry.index).toBe('number');
  expect(typeof entry.label).toBe('string');
  assertCitation(entry.citation);
  return entry;
}

function assertTranscriptEntry(raw: unknown): TranscriptEntry {
  expect(isRecord(raw)).toBe(true);
  const entry = raw as TranscriptEntry;
  expect(['user', 'assistant']).toContain(entry.role);
  expect(typeof entry.text).toBe('string');
  if (entry.role === 'user') {
    const user = entry as TranscriptUserEntry;
    if (user.synthesized !== undefined) expect(user.synthesized).toBe(true);
    return entry;
  }
  const assistant = entry as TranscriptAssistantEntry;
  if (assistant.parts !== undefined) {
    for (const part of assistant.parts) {
      expect(['text', 'viz']).toContain(part.type);
      if (part.type === 'viz') assertRenderSpec(part.spec);
    }
  }
  if (assistant.step_record !== undefined) {
    expect(Array.isArray(assistant.step_record.steps)).toBe(true);
    expect(Array.isArray(assistant.step_record.thinking)).toBe(true);
    expect(typeof assistant.step_record.receipt).toBe('string');
  }
  if (assistant.status !== undefined) {
    expect(['complete', 'awaiting_input', 'cancelled', 'error']).toContain(assistant.status);
  }
  if (assistant.clarify !== undefined) {
    assertClarifySpec(assistant.clarify.spec);
    expect(
      assistant.clarify.answer === null || typeof assistant.clarify.answer === 'string',
    ).toBe(true);
  }
  if (assistant.sources !== undefined) {
    for (const source of assistant.sources) assertSourceEntry(source);
  }
  if (assistant.feedback !== undefined) {
    expect(['up', 'down']).toContain(assistant.feedback.rating);
  }
  return entry;
}

function eventsOf(payload: unknown, key: string): unknown[] {
  expect(isRecord(payload)).toBe(true);
  const events = (payload as Record<string, unknown>)[key];
  expect(Array.isArray(events)).toBe(true);
  return events as unknown[];
}

// ── the fixtures ─────────────────────────────────────────────────────────────

describe('golden protocol fixtures (shared with the backend)', () => {
  test('turn_full: dossier turn — thinking, steps, viz, sources, usage, done', () => {
    const events = eventsOf(load('turn_full'), 'events').map(assertEvent);
    const types = events.map((event) => event.type);
    expect(types[0]).toBe('meta');
    expect(types.at(-1)).toBe('done');
    for (const required of ['thinking', 'step', 'viz', 'delta', 'sources', 'usage']) {
      expect(types).toContain(required);
    }
    const done = events.at(-1);
    expect(done?.type === 'done' && done.data.status).toBe('complete');
  });

  test('turn_clarify: park + resume, the resume reuses the parked message_id', () => {
    const payload = load('turn_clarify');
    const park = eventsOf(payload, 'park').map(assertEvent);
    const resume = eventsOf(payload, 'resume').map(assertEvent);

    const parkDone = park.at(-1);
    expect(parkDone?.type === 'done' && parkDone.data.status).toBe('awaiting_input');
    expect(park.some((event) => event.type === 'clarify')).toBe(true);

    const resumeDone = resume.at(-1);
    expect(resumeDone?.type === 'done' && resumeDone.data.status).toBe('complete');

    const parkMeta = park[0];
    const resumeMeta = resume[0];
    if (parkMeta.type !== 'meta' || resumeMeta.type !== 'meta') throw new Error('meta first');
    expect(resumeMeta.data.message_id).toBe(parkMeta.data.message_id); // G1/G4
    expect(resumeMeta.data.user_message_id).not.toBe(parkMeta.data.user_message_id);
  });

  test('turn_cancelled: prose then the single-shot done(cancelled)', () => {
    const events = eventsOf(load('turn_cancelled'), 'events').map(assertEvent);
    const types = events.map((event) => event.type);
    expect(types.filter((type) => type === 'done')).toHaveLength(1);
    expect(types).not.toContain('error');
    const done = events.at(-1);
    expect(done?.type === 'done' && done.data.status).toBe('cancelled');
    expect(types).toContain('delta');
  });

  test('transcript: the full-fidelity wire shape (§2)', () => {
    const payload = load('transcript');
    const transcript = eventsOf(payload, 'transcript').map(assertTranscriptEntry);

    const assistants = transcript.filter(
      (entry): entry is TranscriptAssistantEntry => entry.role === 'assistant',
    );
    expect(assistants).toHaveLength(3);
    // A1: status required on every MVP2-written entry.
    expect(assistants.every((entry) => entry.status !== undefined)).toBe(true);
    // The clarify turn carries {spec, answer} with the frozen answer.
    const clarified = assistants.find((entry) => entry.clarify !== undefined);
    expect(clarified?.clarify?.answer).toBe('Cost');
    // The synthesized clarify-answer bubble is a first-class user entry.
    const synthesized = transcript.find(
      (entry): entry is TranscriptUserEntry => entry.role === 'user' && entry.synthesized === true,
    );
    expect(synthesized).toBeDefined();
    expect(synthesized?.message_id).toBeDefined();
    // The cancelled turn survives reload with its partial prose.
    const cancelled = assistants.find((entry) => entry.status === 'cancelled');
    expect(cancelled).toBeDefined();
    expect(cancelled?.text.length ?? 0).toBeGreaterThan(0);
  });
});
